# Generated by Django 3.2.15 on 2022-08-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
